// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(VHIDbContext))]
    [Migration("20231230071454_AcceptNull1SoColumnFK")]
    partial class AcceptNull1SoColumnFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Domain.BenhVien", b =>
                {
                    b.Property<int>("ID_BenhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_BenhVien"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBenhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_BenhVien");

                    b.ToTable("BenhVien");
                });

            modelBuilder.Entity("API.Domain.BenhVien_GoiBaoHiem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BenhVienID_BenhVien")
                        .HasColumnType("int");

                    b.Property<int>("GoiBaoHiemID_GoiBaoHiem")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BenhVienID_BenhVien");

                    b.HasIndex("GoiBaoHiemID_GoiBaoHiem");

                    b.ToTable("BenhVien_GoiBaoHiem");
                });

            modelBuilder.Entity("API.Domain.ChiTietChinhSach", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChinhSachID_ChinhSach")
                        .HasColumnType("int");

                    b.Property<string>("DieuKienApDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoiBaoHiemID_GoiBaoHiem")
                        .HasColumnType("int");

                    b.Property<decimal>("HanMucChiTra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChinhSachID_ChinhSach");

                    b.HasIndex("GoiBaoHiemID_GoiBaoHiem");

                    b.ToTable("ChiTietChinhSach");
                });

            modelBuilder.Entity("API.Domain.ChinhSach", b =>
                {
                    b.Property<int>("ID_ChinhSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ChinhSach"));

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<string>("TenChinhSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianPhatHanh")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_ChinhSach");

                    b.ToTable("ChinhSach");
                });

            modelBuilder.Entity("API.Domain.CongTy", b =>
                {
                    b.Property<int>("ID_CongTy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CongTy"));

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoNhaTenDuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_CongTy");

                    b.ToTable("CongTy");
                });

            modelBuilder.Entity("API.Domain.DatLichTuVan", b =>
                {
                    b.Property<int>("ID_YeuCauTuVan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_YeuCauTuVan"));

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachHangID_KhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVien1ID_NhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVien2ID_NhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrangDuyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_YeuCauTuVan");

                    b.HasIndex("KhachHangID_KhachHang");

                    b.HasIndex("NhanVien1ID_NhanVien");

                    b.HasIndex("NhanVien2ID_NhanVien");

                    b.ToTable("DatLichTuVan");
                });

            modelBuilder.Entity("API.Domain.GoiBaoHiem", b =>
                {
                    b.Property<int>("ID_GoiBaoHiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_GoiBaoHiem"));

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayPhatHanh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBaoHiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiHan")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_GoiBaoHiem");

                    b.ToTable("GoiBaoHiem");
                });

            modelBuilder.Entity("API.Domain.HopDong", b =>
                {
                    b.Property<int>("ID_HopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_HopDong"));

                    b.Property<string>("DieuKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaTriHopDong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GoiBaoHiemID_GoiBaoHiem")
                        .HasColumnType("int");

                    b.Property<DateTime>("HieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("KhachHangID_KhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKyKet")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID_NhanVien")
                        .HasColumnType("int");

                    b.Property<int>("PhieuDangKiID_PhieuDangKi")
                        .HasColumnType("int");

                    b.Property<int>("ThoiHan")
                        .HasColumnType("int");

                    b.HasKey("ID_HopDong");

                    b.HasIndex("GoiBaoHiemID_GoiBaoHiem");

                    b.HasIndex("KhachHangID_KhachHang");

                    b.HasIndex("NhanVienID_NhanVien");

                    b.HasIndex("PhieuDangKiID_PhieuDangKi");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("API.Domain.KhachHang", b =>
                {
                    b.Property<int>("ID_KhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_KhachHang"));

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CanNang")
                        .HasColumnType("int");

                    b.Property<string>("ChiTietCongViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChieuCao")
                        .HasColumnType("int");

                    b.Property<int?>("CongTyID_CongTy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoNhaTenDuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanID_TaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThuNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XacThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_KhachHang");

                    b.HasIndex("CongTyID_CongTy");

                    b.HasIndex("TaiKhoanID_TaiKhoan");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("API.Domain.LichSuChiTra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("SoTienChiTra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenBenhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianChiTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("YeuCauChiTraID_YeuCauChiTra")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("YeuCauChiTraID_YeuCauChiTra");

                    b.ToTable("LichSuChiTra");
                });

            modelBuilder.Entity("API.Domain.NhanVien", b =>
                {
                    b.Property<int>("ID_NhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_NhanVien"));

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoNhaTenDuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanID_TaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_NhanVien");

                    b.HasIndex("TaiKhoanID_TaiKhoan");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("API.Domain.PhieuDangKi", b =>
                {
                    b.Property<int>("ID_PhieuDangKi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PhieuDangKi"));

                    b.Property<string>("DiaDiemKiKet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoiBaoHiemID_GoiBaoHiem")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangID_KhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVienID_NhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianKiKet")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrangDuyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToKhaiSucKhoe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PhieuDangKi");

                    b.HasIndex("GoiBaoHiemID_GoiBaoHiem");

                    b.HasIndex("KhachHangID_KhachHang");

                    b.HasIndex("NhanVienID_NhanVien");

                    b.ToTable("PhieuDangKi");
                });

            modelBuilder.Entity("API.Domain.PhieuThanhToanBaoHiem", b =>
                {
                    b.Property<int>("ID_PhieuThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PhieuThanhToan"));

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HopDongID_HopDong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TinhTrangDuyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PhieuThanhToan");

                    b.HasIndex("HopDongID_HopDong");

                    b.ToTable("PhieuThanhToanBaoHiem");
                });

            modelBuilder.Entity("API.Domain.QuanLyBaoHiem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("GoiBaoHiemID_GoiBaoHiem")
                        .HasColumnType("int");

                    b.Property<decimal>("HanMucDaSuDung")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KhachHangID_KhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("GoiBaoHiemID_GoiBaoHiem");

                    b.HasIndex("KhachHangID_KhachHang");

                    b.ToTable("QuanLyBaoHiem");
                });

            modelBuilder.Entity("API.Domain.TaiKhoan", b =>
                {
                    b.Property<int>("ID_TaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TaiKhoan"));

                    b.Property<string>("LoaiTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_TaiKhoan");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("API.Domain.YeuCauChiTra", b =>
                {
                    b.Property<int>("ID_YeuCauChiTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_YeuCauChiTra"));

                    b.Property<string>("ChanDoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HauQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucDieuTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoiQuanHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayYeuCau")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiYeuCau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDieuTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QLBHID")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienYeuCauChiTra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TinhTrangDuyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruongHopChiTra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_YeuCauChiTra");

                    b.HasIndex("QLBHID");

                    b.ToTable("YeuCauChiTra");
                });

            modelBuilder.Entity("API.Domain.BenhVien_GoiBaoHiem", b =>
                {
                    b.HasOne("API.Domain.BenhVien", "BenhVien")
                        .WithMany()
                        .HasForeignKey("BenhVienID_BenhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.GoiBaoHiem", "GoiBaoHiem")
                        .WithMany()
                        .HasForeignKey("GoiBaoHiemID_GoiBaoHiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhVien");

                    b.Navigation("GoiBaoHiem");
                });

            modelBuilder.Entity("API.Domain.ChiTietChinhSach", b =>
                {
                    b.HasOne("API.Domain.ChinhSach", "ChinhSach")
                        .WithMany()
                        .HasForeignKey("ChinhSachID_ChinhSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.GoiBaoHiem", "GoiBaoHiem")
                        .WithMany()
                        .HasForeignKey("GoiBaoHiemID_GoiBaoHiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChinhSach");

                    b.Navigation("GoiBaoHiem");
                });

            modelBuilder.Entity("API.Domain.DatLichTuVan", b =>
                {
                    b.HasOne("API.Domain.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangID_KhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.NhanVien", "NhanVien1")
                        .WithMany()
                        .HasForeignKey("NhanVien1ID_NhanVien");

                    b.HasOne("API.Domain.NhanVien", "NhanVien2")
                        .WithMany()
                        .HasForeignKey("NhanVien2ID_NhanVien");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien1");

                    b.Navigation("NhanVien2");
                });

            modelBuilder.Entity("API.Domain.HopDong", b =>
                {
                    b.HasOne("API.Domain.GoiBaoHiem", "GoiBaoHiem")
                        .WithMany()
                        .HasForeignKey("GoiBaoHiemID_GoiBaoHiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangID_KhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID_NhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.PhieuDangKi", "PhieuDangKi")
                        .WithMany()
                        .HasForeignKey("PhieuDangKiID_PhieuDangKi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiBaoHiem");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("PhieuDangKi");
                });

            modelBuilder.Entity("API.Domain.KhachHang", b =>
                {
                    b.HasOne("API.Domain.CongTy", "CongTy")
                        .WithMany()
                        .HasForeignKey("CongTyID_CongTy");

                    b.HasOne("API.Domain.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanID_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongTy");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("API.Domain.LichSuChiTra", b =>
                {
                    b.HasOne("API.Domain.YeuCauChiTra", "YeuCauChiTra")
                        .WithMany()
                        .HasForeignKey("YeuCauChiTraID_YeuCauChiTra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCauChiTra");
                });

            modelBuilder.Entity("API.Domain.NhanVien", b =>
                {
                    b.HasOne("API.Domain.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanID_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("API.Domain.PhieuDangKi", b =>
                {
                    b.HasOne("API.Domain.GoiBaoHiem", "GoiBaoHiem")
                        .WithMany()
                        .HasForeignKey("GoiBaoHiemID_GoiBaoHiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangID_KhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID_NhanVien");

                    b.Navigation("GoiBaoHiem");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("API.Domain.PhieuThanhToanBaoHiem", b =>
                {
                    b.HasOne("API.Domain.HopDong", "HopDong")
                        .WithMany()
                        .HasForeignKey("HopDongID_HopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("API.Domain.QuanLyBaoHiem", b =>
                {
                    b.HasOne("API.Domain.GoiBaoHiem", "GoiBaoHiem")
                        .WithMany()
                        .HasForeignKey("GoiBaoHiemID_GoiBaoHiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangID_KhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiBaoHiem");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("API.Domain.YeuCauChiTra", b =>
                {
                    b.HasOne("API.Domain.QuanLyBaoHiem", "QLBH")
                        .WithMany()
                        .HasForeignKey("QLBHID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QLBH");
                });
#pragma warning restore 612, 618
        }
    }
}
